### ISSUE TITLE
ErrorCode 2002: Remote worker call failed. Reason: Message Returned exception

### ISSUE THREAD

**Issue by iuri** [qonteo/luna#6]
Trying to send a post request to luna server
{
    "error_code": 2002,
    "detail": "Remote worker call failed. Reason: Message returned exception"
}

Request URI
https://luna.qonteo.com:9000/4/storage/descriptors?estimate_attributes=1&estimate_emotions=1&warped_image=1&external_id=usb_camera_01236&source=usb_camera_0&identification=usb_camera_0

Headers:

<img width="767" alt="Screen Shot 1442-04-26 at 13 55 32" src="https://user-images.githubusercontent.com/64494340/101931701-8b2dfc00-3bb8-11eb-8732-fd194f381778.png">

**Comment by qonteo** [comment]
The problem was caused by the expired license. A new license was updated to the system.

![Screen Shot 1442-05-01 at 08 57 45](https://user-images.githubusercontent.com/64494340/102238296-58477900-3ed4-11eb-8d8e-7bb2a34b694c.png)
